# Site settings
title: Emmanuel
title_init: Emmanuel Morán
title_portfolio: "Portfolio"
email: fnando1995@gmail.com
description: "Your new Engineer!"
keywords: "python,programming"
skills: "AI Engineer Python Developer"
meta_author: Morán Emmanuel

# Google webmaster tools
# google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
# contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  - title: github
    logo: fa-brands fa-fw fa-github
    url: http://github.com/fnando1995
  - title: email
    logo: fa-regular fa-envelope
    url: https://mailto:fnando1995@gmail.com
  - title: curriculum
    logo: fa-regular fa-address-book
    url: https://flowcv.com/resume/wckibrwdn6

# Postal address (add as many lines as necessary)
address:
  - line: Guayaquil
  - line: Ecuador

# # Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
